
;; tests for tetris.lisp
;; two packages in tetris.lisp
;;   :tetris package
;;   :curses package

;; lets get quicklisp 5am up and running

(quicklisp:quickload :fiveam)

;; ask a question 
## > (apropos 'package :fiveam)

*PACKAGE* (bound, PACKAGE)
DEFPACKAGE (fbound)
DELETE-PACKAGE (fbound)
FIND-PACKAGE (fbound)
IN-PACKAGE (fbound)
LIST-ALL-PACKAGES (fbound)
MAKE-PACKAGE (fbound)
PACKAGE
IT.BESE.FIVEAM::PACKAGE-DESIGNATOR
PACKAGE-ERROR
PACKAGE-ERROR-PACKAGE (fbound)
PACKAGE-NAME (fbound)
PACKAGE-NICKNAMES (fbound)
PACKAGE-SHADOWING-SYMBOLS (fbound)
PACKAGE-USE-LIST (fbound)
PACKAGE-USED-BY-LIST (fbound)
PACKAGEP (fbound)
RENAME-PACKAGE (fbound)
IT.BESE.FIVEAM::RUNTIME-PACKAGE (fbound)
SYMBOL-PACKAGE (fbound)
UNUSE-PACKAGE (fbound)
USE-PACKAGE (fbound)
WITH-PACKAGE-ITERATOR (fbound)

(apropos 'function 'list-all-packages)

(list-all-packages)

(#<PACKAGE "UIOP/COMMON-LISP"> #<PACKAGE "QUICKLISP-CLIENT">
 #<PACKAGE "SB-X86-64-ASM"> #<PACKAGE "ASDF/BUNDLE"> #<PACKAGE "UIOP/IMAGE">
 #<PACKAGE "ASDF/FOOTER"> #<PACKAGE "SB-DISASSEM"> #<PACKAGE "SB-BROTHERTREE">
 #<PACKAGE "QL-CCL"> #<PACKAGE "SB-VM"> #<PACKAGE "QL-DIST-USER">
 #<PACKAGE "ASDF/LISP-ACTION"> #<PACKAGE "UIOP/PATHNAME">
 #<PACKAGE "COMMON-LISP"> #<PACKAGE "SB-GRAY"> #<PACKAGE "UIOP/PACKAGE">
 #<PACKAGE "SB-REGALLOC"> #<PACKAGE "ALEXANDRIA"> #<PACKAGE "SB-PRETTY">
 #<PACKAGE "SB-BSD-SOCKETS"> #<PACKAGE "SB-CLTL2"> #<PACKAGE "SB-FASL">
 #<PACKAGE "SWANK-MOP"> #<PACKAGE "SB-BIGNUM"> #<PACKAGE "SWANK-REPL">
 #<PACKAGE "SB-POSIX"> #<PACKAGE "ASDF/INTERFACE">
 #<PACKAGE "UIOP/BACKWARD-DRIVER"> #<PACKAGE "UIOP/STREAM">
 #<PACKAGE "SWANK-MACROSTEP"> #<PACKAGE "ASDF/USER"> #<PACKAGE "SWANK/SBCL">
 #<PACKAGE "SWANK-IO-PACKAGE"> #<PACKAGE "QL-LISPWORKS"> #<PACKAGE "UIOP/OS">
 #<PACKAGE "QL-ALLEGRO"> #<PACKAGE "ASDF/SYSTEM-REGISTRY">
 #<PACKAGE "SB-BSD-SOCKETS-INTERNAL"> #<PACKAGE "SB-LOCKLESS">
 #<PACKAGE "SB-KERNEL"> #<PACKAGE "QL-IMPL">
 #<PACKAGE "SWANK/SOURCE-FILE-CACHE"> #<PACKAGE "TRIVIAL-BACKTRACE">
 #<PACKAGE "UIOP/DRIVER"> #<PACKAGE "SB-PCL"> #<PACKAGE "QL-SCL">
 #<PACKAGE "ASDF/PARSE-DEFSYSTEM"> #<PACKAGE "ASDF/PACKAGE-INFERRED-SYSTEM">
 #<PACKAGE "ASDF/OUTPUT-TRANSLATIONS"> #<PACKAGE "QL-DIST">
 #<PACKAGE "QL-NETWORK"> #<PACKAGE "ASDF/PLAN"> #<PACKAGE "SB-THREAD">
 #<PACKAGE "SWANK/BACKEND"> #<PACKAGE "SB-DEBUG"> #<PACKAGE "SB-DI">
 #<PACKAGE "QL-MKCL"> #<PACKAGE "ASDF/OPERATE"> #<PACKAGE "QL-BUNDLE">
 #<PACKAGE "QL-CLISP"> #<PACKAGE "SB-ALIEN-INTERNALS"> #<PACKAGE "SB-APROF">
 #<PACKAGE "ASDF/CONCATENATE-SOURCE"> #<PACKAGE "IT.BESE.FIVEAM">
 #<PACKAGE "SB-FORMAT"> #<PACKAGE "QL-CLASP"> #<PACKAGE "UIOP/UTILITY">
 #<PACKAGE "KEYWORD"> #<PACKAGE "QL-SBCL"> #<PACKAGE "SWANK/GRAY">
 #<PACKAGE "SB-PROFILE"> #<PACKAGE "ASDF/UPGRADE">
 #<PACKAGE "NET.DIDIERVERNA.ASDF-FLV"> #<PACKAGE "SB-SEQUENCE">
 #<PACKAGE "ASDF/ACTION"> #<PACKAGE "ASDF/SESSION"> #<PACKAGE "ALEXANDRIA-2">
 #<PACKAGE "ASDF/FIND-SYSTEM"> #<PACKAGE "SWANK-LOADER"> #<PACKAGE "SWANK/RPC">
 #<PACKAGE "SB-INT"> #<PACKAGE "SWANK/SOURCE-PATH-PARSER"> #<PACKAGE "SWANK">
 #<PACKAGE "ASDF/BACKWARD-INTERNALS"> #<PACKAGE "ASDF/OPERATION">
 #<PACKAGE "ASDF/SYSTEM"> #<PACKAGE "QL-IMPL-UTIL"> #<PACKAGE "QL-SETUP">
 #<PACKAGE "QL-MINITAR"> #<PACKAGE "QL-CDB"> #<PACKAGE "QL-MEZZANO">
 #<PACKAGE "SB-SYS"> #<PACKAGE "QL-UTIL"> #<PACKAGE "SB-MOP">
 #<PACKAGE "QL-CONFIG"> #<PACKAGE "SB-EVAL"> #<PACKAGE "SB-WALKER">
 #<PACKAGE "QL-ABCL"> #<PACKAGE "QL-INFO"> #<PACKAGE "COMMON-LISP-USER">
 #<PACKAGE "SB-ALIEN"> #<PACKAGE "UIOP/FILESYSTEM"> #<PACKAGE "QL-ECL">
 #<PACKAGE "UIOP/RUN-PROGRAM"> #<PACKAGE "UIOP/CONFIGURATION">
 #<PACKAGE "ASDF/BACKWARD-INTERFACE"> #<PACKAGE "UIOP/LAUNCH-PROGRAM">
 #<PACKAGE "SB-UNIX"> #<PACKAGE "SB-IMPL">
 #<PACKAGE "TRIVIAL-BACKTRACE-SYSTEM"> #<PACKAGE "SB-LOOP">
 #<PACKAGE "UIOP/VERSION"> #<PACKAGE "QL-GUNZIPPER"> #<PACKAGE "ASDF/FORCING">
 #<PACKAGE "SB-UNICODE"> #<PACKAGE "SWANK/MATCH"> #<PACKAGE "UIOP/LISP-BUILD">
 #<PACKAGE "ASDF/SOURCE-REGISTRY"> #<PACKAGE "QL-HTTP"> #<PACKAGE "SB-ASSEM">
 #<PACKAGE "SB-C"> #<PACKAGE "ASDF/COMPONENT"> #<PACKAGE "SWANK-TRACE-DIALOG">
 #<PACKAGE "SB-EXT"> #<PACKAGE "QL-CMUCL"> #<PACKAGE "ASDF/FIND-COMPONENT">
	   #<PACKAGE "QL-PROGRESS"> #<PACKAGE "SB-INTROSPECT">)


(setq *packages* (list-all-packages))


trying to find out how to get documentation about lisp system

specifically it says read :fiveam documentation in source
code


